name: qianshi_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  dio: 5.3.3
  provider: ^6.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  shared_preferences: 2.2.2
  crypto: 3.0.1
  logger: ^1.4.0
  connectivity_plus: 4.0.2
  signalr_netcore: ^1.3.6
  json_serializable: 6.7.1
  # build_runner: ^2.1.5
  # audioplayers: ^5.2.0
  # flutter_meedu_videoplayer: ^4.3.1
  # ffmpeg_kit_flutter: 5.1.0
  photo_view: 0.14.0
  # wechat_camera_picker: ^4.0.2
  # flutter_scankit: ^2.0.2
  http_parser: ^4.0.0
  mime: ^1.0.4
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  permission_handler: ^11.0.1
  flutter_sound: ^9.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

