name: qianshi_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.3.3
  provider: ^6.0.0
  sqflite: ^2.3.0
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  shared_preferences: ^2.2.1
  crypto: ^3.0.1
  # flutter_nb_net: ^2.0.2
  logger: ^2.0.2+1
  connectivity_plus: ^4.0.2
  signalr_netcore: ^1.3.6
  json_serializable: ^6.7.1
  json_annotation: ^4.1.1
  build_runner: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

